// Layer 1 — Config
// Reads environment variables injected by the build/serve process.
// For development without a bundler, values are read from window.__ENV__
// which is injected via a <script> tag generated by a tiny local server,
// OR you can replace the values directly here for local testing.

export const ENV = {
  SUPABASE_URL: window.__ENV__?.SUPABASE_URL ?? '',
  SUPABASE_ANON_KEY: window.__ENV__?.SUPABASE_ANON_KEY ?? '',
};

if (!ENV.SUPABASE_URL || !ENV.SUPABASE_ANON_KEY) {
  console.error('[env] SUPABASE_URL or SUPABASE_ANON_KEY is missing. Check your .env file and server.js.');
}
